name: flutter_modules
description: Flutter Modules Experiment

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  stacked: ^1.9.8
  stacked_services: ^0.7.3  
  nested_list:
    path: nested_list
  tab_buttons:
    path: tab_buttons
  showcase:
    path: showcase  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  stacked_generator: ^0.2.7
  build_runner: ^1.12.2

flutter:
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs  
