name: flutter_modules
description: Flutter Modules Experiment

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^3.0.2+1
  responsive_builder: ^0.4.1
  nested_list:
    path: nested_list
  tab_buttons:
    path: tab_buttons
  showcase:
    path: showcase  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
