name: source_code_view
description: Source Code View module.

version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_syntax_view: ^3.2.2
  animate_icons: ^1.0.0
  url_launcher: ^6.0.2
  shimmer: ^1.1.2
  package_info_plus: ^1.0.0
  pubspec_parse: ^1.0.0
  common_ui:
    path: ../common_ui

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.source_code_view
    iosBundleIdentifier: com.example.sourceCodeView
